/**
 * Project facts — the numbers that used to drift in `docs/STATUS.md`.
 *
 * `project-facts.json` is generated by `scripts/status-refresh.ts` (the only
 * writer) and consumed by the status document and the vault map of content, so
 * the date, the document counts and the test counts can never disagree between
 * the repository, Notion and Obsidian. Counts that need infrastructure to
 * measure (API integration, browser E2E) are preserved from the existing file
 * and only updated when a refresh is run with them available.
 */

import { existsSync } from 'node:fs';
import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

export interface ProjectFacts {
  /** Package version, from the root package.json. */
  version: string;
  /** ISO date of the last refresh. */
  updated: string;
  /** Canonical documents mirrored to both targets (registry + ADRs). */
  documents: number;
  /** Human breakdown, e.g. `17 documents + 8 ADRs`. */
  documentsBreakdown: string;
  /** Documents that live inside `docs/` only. */
  docsFolder: number;
  /** Total unit tests (packages + scripts). */
  unitTests: number;
  /** Human breakdown, e.g. `shared 8 · API 120 · web 46 · scripts 13`. */
  unitTestsBreakdown: string;
  /** API integration tests (needs Docker; preserved across refreshes). */
  apiIntegration: number;
  /** Browser E2E tests (needs Playwright; preserved across refreshes). */
  browserE2e: number;
}

export const FACTS_FILE = 'project-facts.json';

/** Fallback used when the facts file does not exist yet. */
export function defaultFacts(): ProjectFacts {
  return {
    version: '0.1.0',
    updated: '1970-01-01',
    documents: 0,
    documentsBreakdown: '0 documents + 0 ADRs',
    docsFolder: 0,
    unitTests: 0,
    unitTestsBreakdown: '',
    apiIntegration: 0,
    browserE2e: 0,
  };
}

export async function readProjectFacts(root: string): Promise<ProjectFacts> {
  const path = join(root, FACTS_FILE);

  if (!existsSync(path)) {
    return defaultFacts();
  }

  return {
    ...defaultFacts(),
    ...(JSON.parse(await readFile(path, 'utf8')) as Partial<ProjectFacts>),
  };
}

export async function writeProjectFacts(root: string, facts: ProjectFacts): Promise<void> {
  await writeFile(join(root, FACTS_FILE), `${JSON.stringify(facts, null, 2)}\n`, 'utf8');
}

/** Matches a marked fact region: `<!--f:key-->value<!--/f-->`. */
const FACT_MARKER = /<!--\s*f:([a-z0-9-]+)\s*-->([\s\S]*?)<!--\s*\/f\s*-->/g;

/**
 * Replaces the marked fact regions. The document keeps the resolved value
 * between invisible HTML comments, so the repository shows real numbers while
 * the refresh can always find and update them:
 *
 *   <!--f:date-->2026-10-05<!--/f-->
 *
 * Unknown keys are left untouched so a typo is visible instead of erased.
 */
export function applyFacts(markdown: string, facts: ProjectFacts): string {
  const values = factsToPlaceholders(facts);

  return markdown.replace(FACT_MARKER, (match, key: string) =>
    values[key] !== undefined ? `<!--f:${key}-->${values[key]}<!--/f-->` : match,
  );
}

/** Removes the fact markers, keeping the resolved value (used when publishing). */
export function stripFactMarkers(markdown: string): string {
  return markdown.replace(FACT_MARKER, (_match, _key: string, value: string) => value.trim());
}

/** Placeholder values derived from the facts, for the status document. */
export function factsToPlaceholders(facts: ProjectFacts): Record<string, string> {
  return {
    date: facts.updated,
    documents: String(facts.documents),
    'documents-breakdown': facts.documentsBreakdown,
    'docs-folder': String(facts.docsFolder),
    'unit-tests': String(facts.unitTests),
    'unit-tests-ratio': `${facts.unitTests}/${facts.unitTests}`,
    'unit-tests-breakdown': facts.unitTestsBreakdown,
    'api-integration': String(facts.apiIntegration),
    'api-integration-ratio': `${facts.apiIntegration}/${facts.apiIntegration}`,
    'browser-e2e': String(facts.browserE2e),
    'browser-e2e-ratio': `${facts.browserE2e}/${facts.browserE2e}`,
  };
}
